package com.featuremodule.core.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

enum class ColorsLight(val scheme: ColorScheme) {
    Default(
        lightColorScheme(
            primary = Color(0xFF6650A4),
            secondary = Color(0xFF625B71),
            tertiary = Color(0xFF7D5260),
        ),
    ),
    Red(
        lightColorScheme(
            primary = Color(0xFFA50011),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFEA001D),
            onPrimaryContainer = Color(0xFFFFFFFF),
            secondary = Color(0xFFB32826),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFFF776C),
            onSecondaryContainer = Color(0xFF350002),
            tertiary = Color(0xFF774300),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFAB6300),
            onTertiaryContainer = Color(0xFFFFFFFF),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF410002),
            background = Color(0xFFFFF8F7),
            onBackground = Color(0xFF2A1614),
            surface = Color(0xFFFFF8F7),
            onSurface = Color(0xFF2A1614),
            surfaceVariant = Color(0xFFFFDAD6),
            onSurfaceVariant = Color(0xFF5F3F3B),
            outline = Color(0xFF946E6A),
            outlineVariant = Color(0xFFE9BCB7),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF412B28),
            inverseOnSurface = Color(0xFFFFEDEA),
            inversePrimary = Color(0xFFFFB4AC),
            surfaceDim = Color(0xFFF6D2CE),
            surfaceBright = Color(0xFFFFF8F7),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFFFF0EF),
            surfaceContainer = Color(0xFFFFE9E6),
            surfaceContainerHigh = Color(0xFFFFE2DE),
            surfaceContainerHighest = Color(0xFFFFDAD6),
        ),
    ),
    Green(
        lightColorScheme(
            primary = Color(0xFF3A693B),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFBBF0B6),
            onPrimaryContainer = Color(0xFF002105),
            secondary = Color(0xFF52634F),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFD5E8CF),
            onSecondaryContainer = Color(0xFF101F10),
            tertiary = Color(0xFF39656B),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFBCEBF1),
            onTertiaryContainer = Color(0xFF001F23),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF410002),
            background = Color(0xFFF7FBF1),
            onBackground = Color(0xFF181D17),
            surface = Color(0xFFF7FBF1),
            onSurface = Color(0xFF181D17),
            surfaceVariant = Color(0xFFDEE5D9),
            onSurfaceVariant = Color(0xFF424940),
            outline = Color(0xFF72796F),
            outlineVariant = Color(0xFFC2C9BD),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF2D322C),
            inverseOnSurface = Color(0xFFEEF2E9),
            inversePrimary = Color(0xFFA0D49B),
            surfaceDim = Color(0xFFD7DBD2),
            surfaceBright = Color(0xFFF7FBF1),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFF1F5EC),
            surfaceContainer = Color(0xFFEBEFE6),
            surfaceContainerHigh = Color(0xFFE6E9E0),
            surfaceContainerHighest = Color(0xFFE0E4DB),
        ),
    )
}

enum class ColorsDark(val scheme: ColorScheme) {
    Default(
        darkColorScheme(
            primary = Color(0xFFD0BCFF),
            secondary = Color(0xFFCCC2DC),
            tertiary = Color(0xFFEFB8C8),
        ),
    ),
    Red(
        darkColorScheme(
            primary = Color(0xFFFFB4AC),
            onPrimary = Color(0xFF690007),
            primaryContainer = Color(0xFFDF001B),
            onPrimaryContainer = Color(0xFFFFFFFF),
            secondary = Color(0xFFFFB4AC),
            onSecondary = Color(0xFF690007),
            secondaryContainer = Color(0xFF86000C),
            onSecondaryContainer = Color(0xFFFFC8C2),
            tertiary = Color(0xFFFFB873),
            onTertiary = Color(0xFF4B2800),
            tertiaryContainer = Color(0xFFA35E00),
            onTertiaryContainer = Color(0xFFFFFFFF),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            background = Color(0xFF210E0D),
            onBackground = Color(0xFFFFDAD6),
            surface = Color(0xFF210E0D),
            onSurface = Color(0xFFFFDAD6),
            surfaceVariant = Color(0xFF5F3F3B),
            onSurfaceVariant = Color(0xFFE9BCB7),
            outline = Color(0xFFB08783),
            outlineVariant = Color(0xFF5F3F3B),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFFFDAD6),
            inverseOnSurface = Color(0xFF412B28),
            inversePrimary = Color(0xFFC00016),
            surfaceDim = Color(0xFF210E0D),
            surfaceBright = Color(0xFF4B3331),
            surfaceContainerLowest = Color(0xFF1B0908),
            surfaceContainerLow = Color(0xFF2A1614),
            surfaceContainer = Color(0xFF2E1A18),
            surfaceContainerHigh = Color(0xFF3A2422),
            surfaceContainerHighest = Color(0xFF462F2D),
        ),
    ),
    Green(
        darkColorScheme(
            primary = Color(0xFFA0D49B),
            onPrimary = Color(0xFF073910),
            primaryContainer = Color(0xFF225025),
            onPrimaryContainer = Color(0xFFBBF0B6),
            secondary = Color(0xFFB9CCB4),
            onSecondary = Color(0xFF253423),
            secondaryContainer = Color(0xFF3B4B39),
            onSecondaryContainer = Color(0xFFD5E8CF),
            tertiary = Color(0xFFA1CED5),
            onTertiary = Color(0xFF00363C),
            tertiaryContainer = Color(0xFF1F4D53),
            onTertiaryContainer = Color(0xFFBCEBF1),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            background = Color(0xFF10140F),
            onBackground = Color(0xFFE0E4DB),
            surface = Color(0xFF10140F),
            onSurface = Color(0xFFE0E4DB),
            surfaceVariant = Color(0xFF424940),
            onSurfaceVariant = Color(0xFFC2C9BD),
            outline = Color(0xFF8C9388),
            outlineVariant = Color(0xFF424940),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFE0E4DB),
            inverseOnSurface = Color(0xFF2D322C),
            inversePrimary = Color(0xFF3A693B),
            surfaceDim = Color(0xFF10140F),
            surfaceBright = Color(0xFF363A34),
            surfaceContainerLowest = Color(0xFF0B0F0A),
            surfaceContainerLow = Color(0xFF181D17),
            surfaceContainer = Color(0xFF1C211B),
            surfaceContainerHigh = Color(0xFF272B25),
            surfaceContainerHighest = Color(0xFF323630),
        ),
    )
}

/** Sets light or dark theme as active, or switches it with system */
enum class ThemeStyle {
    Light,
    Dark,
    System
}
